### ISSUE TITLE
为什么不修改此接口适应coinapi的交易功能呢？

### ISSUE THREAD

**Issue by franklili3** [vnpy/vnpy_coinapi#3]
coinapi对接了250个交易所，使用统一的交易接口，为什么不修改此接口适应coinapi的交易功能呢？

**Comment by vn-crypto** [comment]
hi, i just checked coinapi website to find they are providing a new EMS trading API, this seems to be a very nice function.

you are very welcome to send PR for this parts, I will merge them.
